apiVersion: "authentication.istio.io/v1alpha1"
kind: "Policy"
metadata:
  name: company-auth
  namespace: demo
spec:
  targets:
  - name: company
  origins:
  - jwt:
      issuer: 192.168.99.100
      audiences:
      - company
      jwksUri: https://s3.amazonaws.com/fitstation-demo/jwks
  principalBinding: USE_ORIGIN
