---
apiVersion: config.istio.io/v1alpha2
kind: listchecker
metadata:
  name: whitelist
  namespace: demo
spec:
  # providerUrl: ordinarily black and white lists are maintained
  # externally and fetched asynchronously using the providerUrl.
  overrides: ["user"]  # overrides provide a static list
  blacklist: false
---
apiVersion: config.istio.io/v1alpha2
kind: listentry
metadata:
  name: appname
  namespace: demo
spec:
  value: source.labels["app"]
---
apiVersion: config.istio.io/v1alpha2
kind: rule
metadata:
  name: checkname
  namespace: demo
spec:
  match: destination.labels["app"] == "product"
  actions:
  - handler: whitelist.listchecker
    instances:
    - appname.listentry
---